# Generated by Django 5.2.6 on 2025-10-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='imagem_capitulo',
            field=models.ImageField(blank=True, null=True, upload_to='historias/'),
        ),
    ]
