# Generated by Django 5.2.6 on 2025-10-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_album_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemDecorativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('imagem', models.ImageField(upload_to='decoracao/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
