# Generated by Django 5.2.6 on 2025-10-03 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagemdecorativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(blank=True, max_length=200)),
                ('arquivo_audio', models.FileField(upload_to='musicas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor número toca primeiro')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
